Repository StPfeffer/projeto-quinta-tailwindcss, pull requests merged in 2022-11, with the labels that each got.

#8 fixed sidebar hover colors
  components/sidebar.ejs
Labels: bug

#10 fixed sidebar not opening
  views/ajuda.ejs
  views/configuracoes.ejs
  views/inicio.ejs
  views/notificacoes.ejs
  views/perfil.ejs
  views/projetos.ejs
Labels: bug

#11 Desenvolvimento inicial do componente projeto
  components/project.ejs
  package-lock.json
  public/images/Screenshot_1.png
  public/styles/style.css
  views/projetos.ejs
Labels: enhancement

#13 Atividades page and sidebar fix
  app.js
  components/sidebar.ejs
  public/images/file.svg
  routes/atividades.js
  views/ajuda.ejs
  views/atividades.ejs
  views/configuracoes.ejs
  views/inicio.ejs
  views/notificacoes.ejs
  views/perfil.ejs
  views/projetos.ejs
Labels: bug, enhancement

#21 Updated "Perfil"
  public/images/edit.svg
  public/styles/style.css
  views/perfil.ejs
Labels: enhancement

#22 sla mano
  app.js
  components/404.ejs
  public/styles/style.css
  routes/test.js
  views/adicionar_sala.ejs
  views/ajuda.ejs
  views/configuracoes.ejs
  views/notificacoes.ejs
  views/salas.ejs
  views/test.ejs
Labels: enhancement
